name: SWorld
main: SWorld\SWorld
version: 1.2.0
api: [3.0.0-ALPHA3,3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
load: POSTWORLD
author: 18WYJ2 & boybook

commands:
 w:
  description: Change world
  
 lw:
  description: See list of worlds

 load:
  permission: World.load
  description: Load a world

 unload:
  permission: World.unload
  description: Unload a world

  
permissions:
 World:
  default: op
  description: SWorld permission
  children:
     World.load:
      default: op
      description: load a world
     World.unload:
      default: op
      description: unload a world
    
